<?php /* Smarty version 2.6.20, created on 2016-03-07 13:27:48
         compiled from video-tag.tpl */

$this->_cache_serials['C:\xampp\htdocs\haivl/Smarty/templates_c\%%1E^1E4^1E476FA0%%video-tag.tpl.inc'] = 'bab0b1baef41c63421b83a0a521257dd';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_advanced_video_list', 'video-tag.tpl', 97, false),)), $this); ?>
<?php
function _smarty_tplfunc_bab0b1baef41c63421b83a0a521257dd_0(&$_smarty)
{
echo smarty_get_advanced_video_list(array('assignto' => 'advanced_video_list','limit' => 7), $_smarty);
}



?>
