<?php /* Smarty version 2.6.20, created on 2016-03-05 11:20:11
         compiled from video-new.tpl */

$this->_cache_serials['C:\xampp\htdocs\haivl/Smarty/templates_c\%%26^269^269879B4%%video-new.tpl.inc'] = '99f052690ed39713ee23e0aa7f0511f3';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_advanced_video_list', 'video-new.tpl', 6, false),)), $this); ?>
<?php
function _smarty_tplfunc_99f052690ed39713ee23e0aa7f0511f3_0(&$_smarty)
{
echo smarty_get_advanced_video_list(array('assignto' => 'advanced_video_list','tag' => 'Hot','limit' => 5), $_smarty);
}



?>
