<?php /* Smarty version 2.6.20, created on 2016-03-04 08:13:02
         compiled from header.tpl */

$this->_cache_serials['/var/www/html/haivl/Smarty/templates_c/%%F7^F7F^F7F34188%%header.tpl.inc'] = 'ad3fe4d5615632fe183e317437f7a934';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'default', 'header.tpl', 73, false),array('modifier', 'escape', 'header.tpl', 90, false),array('function', 'dropdown_menu_video_categories', 'header.tpl', 321, false),array('function', 'dropdown_menu_article_categories', 'header.tpl', 329, false),)), $this); ?>
<?php
function _smarty_tplfunc_ad3fe4d5615632fe183e317437f7a934_0(&$_smarty)
{
echo smarty_art_html_list_categories(array('max_levels' => 3), $_smarty);
}



?>
